GET http://127.0.0.1:8080/person

###
POST http://127.0.0.1:8080/add/person
Content-Type: application/json

{
 "id": "2",
 "name": "Raj",
 "cars": [
        "BMW",
        "AUDI",
        "HONDA",
        "SUZUKI",
        "JEEP",
        "NSX"
]
}

###
POST http://127.0.0.1:8080/user
Content-Type: application/json

{
  "name": "Ridham"
}

###
GET http://127.0.0.1:8080/user/Mann
Content-Type: application/json

###
POST http://0.0.0.0:8080/add/user
Content-Type: application/json

{
  "firstName" : "Smit",
  "lastName" : "Kalkani",
  "email" : "smitnash@gmail.com",
  "password" : "9099850857"
}

###
GET https://foodmenuapp-pgokju5beq-el.a.run.app/user/smitnash@gmail.com